# install watchtower : ansible-playbook -i ./hosts.yaml ./setup_3_watchtower.yml

- hosts: all
  become: "yes"
  vars:
    poll_interval: 120
  tasks:
    - name: Install Watchtower
      docker_container:
        name: watchtower
        image: containrrr/watchtower
        labels:
          com.centurylinklabs.watchtower.enable: "false"
        state: started
        restart_policy: unless-stopped
        network_mode: host
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /etc/docker/config.json:/config.json
        env:
          WATCHTOWER_POLL_INTERVAL: "'{{ poll_interval }}'"
          WATCHTOWER_CLEANUP: "true"
          WATCHTOWER_INCLUDE_STOPPED: "true"
          WATCHTOWER_INCLUDE_RESTARTING: "true"
          WATCHTOWER_LABEL_ENABLE: "1" # monitor containers with the enable label set to true
          WATCHTOWER_NOTIFICATIONS: "email"
          WATCHTOWER_NOTIFICATION_EMAIL_FROM: "{{ mail_user }}"
          WATCHTOWER_NOTIFICATION_EMAIL_TO: "{{ mail_recipient }}"
          WATCHTOWER_NOTIFICATION_EMAIL_SERVER: "{{ mail_server }}"
          WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: "587"
          WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: "{{ mail_user }}"
          WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: "{{ mail_password }}"
          WATCHTOWER_NOTIFICATION_EMAIL_DELAY: "2"
          #REPO_USER: "{{ghcr_user}}"
          #REPO_PASS: "{{ghcr_token}}"
